services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      timeout: 5s
      retries: 5

  prefect-server:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_API_PORT: 4200
    env_file:
      - .env
    command: >
      /bin/sh -c "
      echo 'Initializing database...';
      prefect server database upgrade;
      echo 'Starting Prefect server...';
      prefect server start
      "
    ports:
      - "4200:4200"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; requests.get(\"http://localhost:4200/api/health\").raise_for_status()' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

volumes:
  postgres_data: